import * as path from 'node:path';
import type { ResolvedServiceDeps } from './types.js';

// The version-independent launcher shared by the launchd (macOS) and systemd (Linux)
// installers. The service manager runs THIS script, not the bot directly, so a node
// version bump (via nvm) never leaves the plist/unit pointing at a dead binary path.

export const RUN_SCRIPT_NAME = 'run.sh';

export function runScriptPath(d: ResolvedServiceDeps): string {
  return path.join(d.baseDir, RUN_SCRIPT_NAME);
}

// Prefer nvm's default node (so a node upgrade never breaks the service); when nvm is
// absent, fall back to the install-time node directory on PATH. Either branch then
// exec's the globally-installed `discord-agent-bridge` bin (which lives alongside the
// active node's bin in both cases).
export function buildRunScript(d: ResolvedServiceDeps): string {
  return (
    [
      '#!/bin/bash',
      '# Generated by `discord-agent-bridge service install`. Removed on uninstall.',
      '# Loads a version-independent node, then starts the bot.',
      'export NVM_DIR="$HOME/.nvm"',
      'if [ -s "$NVM_DIR/nvm.sh" ]; then',
      '  . "$NVM_DIR/nvm.sh"',
      '  nvm use default >/dev/null 2>&1 || nvm use node >/dev/null 2>&1 || true',
      'else',
      `  export PATH="${d.nodeDir}:$PATH"`,
      'fi',
      'exec discord-agent-bridge',
      '',
    ].join('\n')
  );
}

// Write run.sh (0755) into the base dir, creating the dir first. Returns its path.
export function ensureRunScript(d: ResolvedServiceDeps): string {
  d.fs.mkdirp(d.baseDir);
  const target = runScriptPath(d);
  d.fs.writeFile(target, buildRunScript(d), 0o755);
  d.fs.chmod(target, 0o755);
  return target;
}
