import * as path from 'node:path';
import type { ResolvedServiceDeps } from './types.js';

// The version-independent launcher shared by the launchd (macOS) and systemd (Linux)
// installers. The service manager runs THIS script, not the bot directly, so a node
// version bump (via nvm) never leaves the plist/unit pointing at a dead binary path.

export const RUN_SCRIPT_NAME = 'run.sh';

export function runScriptPath(d: ResolvedServiceDeps): string {
  return path.join(d.baseDir, RUN_SCRIPT_NAME);
}

// Prefer nvm's default/current Node dynamically (so a Node upgrade never breaks the
// service); when nvm is absent or has no usable alias, fall back to the install-time
// node directory while preserving the inherited PATH. Either branch then exec's the
// globally-installed `discord-agent-bridge` bin (which lives alongside active Node).
export function buildRunScript(d: ResolvedServiceDeps): string {
  return (
    [
      '#!/bin/bash',
      '# Generated by `discord-agent-bridge service install`. Removed on uninstall.',
      '# Loads a version-independent node, then starts the bot.',
      'export NVM_DIR="$HOME/.nvm"',
      'nvm_node=""',
      'if [ -s "$NVM_DIR/nvm.sh" ]; then',
      '  . "$NVM_DIR/nvm.sh"',
      '  nvm_node="$(nvm which default 2>/dev/null || true)"',
      '  if [ ! -x "$nvm_node" ]; then',
      '    nvm_node="$(nvm which node 2>/dev/null || true)"',
      '  fi',
      '  if [ -x "$nvm_node" ]; then',
      '    export PATH="$(dirname "$nvm_node"):$PATH"',
      '  fi',
      'fi',
      // If nvm provided no executable, prefer the Node that installed this CLI over an
      // unrelated system Node already on PATH. Keep the inherited path only when the
      // install-time directory itself is no longer valid.
      `if [ ! -x "$nvm_node" ] && [ -x "${path.join(d.nodeDir, 'node')}" ]; then`,
      `  export PATH="${d.nodeDir}:$PATH"`,
      'fi',
      // User-local CLI bins (grok, claude, cargo tools, Homebrew). $HOME-relative — portable.
      'export PATH="$HOME/.local/bin:$HOME/.grok/bin:$HOME/.cargo/bin:/opt/homebrew/bin:/home/linuxbrew/.linuxbrew/bin:/usr/local/bin:$PATH"',
      // Mark this process as launched by a KeepAlive/Restart supervisor (launchd/systemd).
      // run.sh is ONLY generated for those, so the marker precisely means "exiting me
      // relaunches me" — the auto-updater reads it to pick method A (exit-only) restart
      // and never escape the supervisor with a detached respawn (§3.2).
      'export DAB_SUPERVISED=1',
      'exec discord-agent-bridge',
      '',
    ].join('\n')
  );
}

// Write run.sh (0755) into the base dir, creating the dir first. Returns its path.
export function ensureRunScript(d: ResolvedServiceDeps): string {
  d.fs.mkdirp(d.baseDir);
  const target = runScriptPath(d);
  d.fs.writeFile(target, buildRunScript(d), 0o755);
  d.fs.chmod(target, 0o755);
  return target;
}
