#!/bin/bash
# install.sh — build `dab`, install it as a per-user launchd LaunchAgent.
#
# Why a launcher script + baked absolute paths (root cause, not workaround):
#   - launchd hands children a minimal PATH (~ /usr/bin:/bin), so node/codex/grok
#     (Homebrew / user-local) are unfindable — run.sh prepends an explicit PATH.
#   - launchd's default cwd is "/", but the Claude sidecar spawn resolves paths
#     relative to the repo checkout (findRepoRoot) — run.sh cd's to the repo root.
#   - $HOME is NOT expanded inside a plist, so absolute paths are baked at install.
#
# ponytail: assumes no XML/shell-hostile chars (& < > " ' space) in $HOME — home
#   paths with those need XML-escaping in the plist and quoting review in run.sh.
#   Upgrade path: add an xml() escaper mirroring src/service/launchd.ts:27 if needed.
# ponytail: secrets live only in ~/.dab/env (0600); the 0644 plist carries HOME only.

set -euo pipefail

LABEL="com.discord-agent-bridge"
DAB_HOME="$HOME/.dab"
BIN_DIR="$DAB_HOME/bin"
LOG_DIR="$DAB_HOME/logs"
ENV_FILE="$DAB_HOME/env"
RUN_SCRIPT="$DAB_HOME/run.sh"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
OUT_LOG="$LOG_DIR/agent.out.log"
ERR_LOG="$LOG_DIR/agent.err.log"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SWIFT_DIR="$REPO_ROOT/swift"
ENV_EXAMPLE="$SWIFT_DIR/deploy/env.example"
BUILT_BIN="$SWIFT_DIR/.build/release/dab"

DRY_RUN=0
[ "${1:-}" = "--dry-run" ] && DRY_RUN=1

log() { printf '%s\n' "$*"; }

# run.sh is what launchd executes. It fixes PATH (child CLI discovery) and cwd
# (sidecar repo-relative paths), sources the 0600 env, then exec's dab.
gen_run_script() {
  local out="$1"
  cat > "$out" <<EOF
#!/bin/bash
# Generated by swift/scripts/install.sh — removed on uninstall. Do not edit by hand.
# launchd runs THIS, not dab directly: PATH + cwd are set here (see install.sh header).
export PATH="/opt/homebrew/bin:/usr/local/bin:$HOME/.local/bin:$HOME/.grok/bin:$HOME/.cargo/bin:/usr/bin:/bin:\$PATH"
if [ -f "$ENV_FILE" ]; then
  set -a
  . "$ENV_FILE"
  set +a
fi
cd "$REPO_ROOT"
exec "$BIN_DIR/dab"
EOF
  chmod 0755 "$out"
}

gen_plist() {
  local out="$1"
  cat > "$out" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>$RUN_SCRIPT</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>HOME</key>
    <string>$HOME</string>
  </dict>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>$OUT_LOG</string>
  <key>StandardErrorPath</key>
  <string>$ERR_LOG</string>
</dict>
</plist>
EOF
  chmod 0644 "$out"
}

# Validate generated artifacts. plutil -lint is the hard gate; bash -n catches
# syntax errors in run.sh; the reference checks confirm what the plist points at.
selfcheck() {
  local plist="$1" runsh="$2" require_bin="$3"
  plutil -lint "$plist"
  bash -n "$runsh"
  if [ -x "$BIN_DIR/dab" ]; then
    log "  ok: $BIN_DIR/dab (referenced dab binary present)"
  elif [ "$require_bin" = "1" ]; then
    log "FATAL: $BIN_DIR/dab missing after build" >&2
    return 1
  else
    log "  note: $BIN_DIR/dab not present yet (run install.sh without --dry-run to build)"
  fi
}

if [ "$DRY_RUN" = "1" ]; then
  log "== dry-run: generate + validate artifacts, no build, no launchctl load =="
  tmp="$(mktemp -d)"
  trap 'rm -rf "$tmp"' EXIT
  gen_run_script "$tmp/run.sh"
  gen_plist "$tmp/$LABEL.plist"
  selfcheck "$tmp/$LABEL.plist" "$tmp/run.sh" 0
  log "  ok: plutil -lint passed; run.sh bash -n passed"
  log "  repo root (run.sh cwd): $REPO_ROOT"
  log "  plist -> run.sh:        $RUN_SCRIPT"
  log "  plist logs:             $OUT_LOG , $ERR_LOG"
  log "  generated (temp) plist: $tmp/$LABEL.plist"
  log "  generated (temp) run.sh: $tmp/run.sh"
  log "dry-run OK"
  exit 0
fi

log "== build (release) =="
swift build -c release --package-path "$SWIFT_DIR"
[ -x "$BUILT_BIN" ] || { log "FATAL: build produced no $BUILT_BIN" >&2; exit 1; }

log "== install to $DAB_HOME =="
mkdir -p "$BIN_DIR" "$LOG_DIR" "$(dirname "$PLIST")"
cp "$BUILT_BIN" "$BIN_DIR/dab"
chmod 0755 "$BIN_DIR/dab"

if [ ! -f "$ENV_FILE" ]; then
  cp "$ENV_EXAMPLE" "$ENV_FILE"
  chmod 0600 "$ENV_FILE"
  log "  created $ENV_FILE (0600) — fill in DISCORD_BOT_TOKEN and DAB_* before it can log in"
else
  log "  kept existing $ENV_FILE"
fi

gen_run_script "$RUN_SCRIPT"
gen_plist "$PLIST"
selfcheck "$PLIST" "$RUN_SCRIPT" 1

log "== register with launchd =="
launchctl unload "$PLIST" 2>/dev/null || true
launchctl load -w "$PLIST"

log "installed and loaded. Runs at login and is kept alive."
log "  plist: $PLIST"
log "  logs:  $OUT_LOG"
log "         $ERR_LOG"
log "  edit secrets: $ENV_FILE  (then: launchctl unload \"$PLIST\" && launchctl load -w \"$PLIST\")"
