#!/bin/bash
# install-linux.sh — build `dab`, install it as a systemd --user unit.
#
# Mirrors src/service/systemd.ts + swift/scripts/install.sh (macOS launchd):
#   - systemd --user unit with Restart=always (crash relaunch)
#   - run.sh fixes PATH (minimal user-unit PATH) and cwd (sidecar repo-relative paths)
#   - best-effort loginctl enable-linger so the unit can start before interactive login
#
# ponytail: assumes no shell-hostile chars in $HOME for paths baked into unit/run.sh.
#   Upgrade path: quote/escape if needed (same ceiling as install.sh).

set -euo pipefail

SERVICE_NAME="discord-agent-bridge"
DAB_HOME="$HOME/.dab"
BIN_DIR="$DAB_HOME/bin"
LOG_DIR="$DAB_HOME/logs"
ENV_FILE="$DAB_HOME/env"
RUN_SCRIPT="$DAB_HOME/run.sh"
UNIT_DIR="$HOME/.config/systemd/user"
UNIT_FILE="$UNIT_DIR/${SERVICE_NAME}.service"
OUT_LOG="$LOG_DIR/agent.out.log"
ERR_LOG="$LOG_DIR/agent.err.log"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SWIFT_DIR="$REPO_ROOT/swift"
ENV_EXAMPLE="$SWIFT_DIR/deploy/env.example"
BUILT_BIN="$SWIFT_DIR/.build/release/dab"

DRY_RUN=0
[ "${1:-}" = "--dry-run" ] && DRY_RUN=1

log() { printf '%s\n' "$*"; }

# run.sh is what systemd ExecStart runs. PATH + cwd + env, then exec dab.
# DAB_SUPERVISED=1 matches TS runScript.ts so auto-update can prefer exit-only restart.
gen_run_script() {
  local out="$1"
  cat > "$out" <<EOF
#!/bin/bash
# Generated by swift/scripts/install-linux.sh — removed on uninstall. Do not edit by hand.
# systemd --user runs THIS, not dab directly: PATH + cwd are set here.
export PATH="\$HOME/.local/bin:\$HOME/.grok/bin:\$HOME/.cargo/bin:/home/linuxbrew/.linuxbrew/bin:/usr/local/bin:/usr/bin:/bin:\$PATH"
export DAB_SUPERVISED=1
if [ -f "$ENV_FILE" ]; then
  set -a
  . "$ENV_FILE"
  set +a
fi
cd "$REPO_ROOT"
exec "$BIN_DIR/dab"
EOF
  chmod 0755 "$out"
}

gen_unit() {
  local out="$1"
  cat > "$out" <<EOF
[Unit]
Description=discord-agent-bridge (Discord <-> agent bridge)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/bin/bash $RUN_SCRIPT
Restart=always
RestartSec=5
StandardOutput=append:$OUT_LOG
StandardError=append:$ERR_LOG

[Install]
WantedBy=default.target
EOF
  chmod 0644 "$out"
}

selfcheck() {
  local unit="$1" runsh="$2" require_bin="$3"
  bash -n "$runsh"
  # Soft checks — unit syntax is plain INI; systemd-analyze may be unavailable in CI.
  if command -v systemd-analyze >/dev/null 2>&1; then
    systemd-analyze --user verify "$unit" 2>/dev/null || \
      log "  note: systemd-analyze --user verify skipped/failed (ok if no user bus)"
  fi
  if [ -x "$BIN_DIR/dab" ]; then
    log "  ok: $BIN_DIR/dab (referenced dab binary present)"
  elif [ "$require_bin" = "1" ]; then
    log "FATAL: $BIN_DIR/dab missing after build" >&2
    return 1
  else
    log "  note: $BIN_DIR/dab not present yet (run install-linux.sh without --dry-run to build)"
  fi
}

if [ "$DRY_RUN" = "1" ]; then
  log "== dry-run: generate + validate artifacts, no build, no systemctl =="
  tmp="$(mktemp -d)"
  trap 'rm -rf "$tmp"' EXIT
  gen_run_script "$tmp/run.sh"
  gen_unit "$tmp/${SERVICE_NAME}.service"
  selfcheck "$tmp/${SERVICE_NAME}.service" "$tmp/run.sh" 0
  log "  ok: run.sh bash -n passed"
  log "  repo root (run.sh cwd): $REPO_ROOT"
  log "  unit -> run.sh:         $RUN_SCRIPT"
  log "  unit logs:              $OUT_LOG , $ERR_LOG"
  log "  generated (temp) unit:  $tmp/${SERVICE_NAME}.service"
  log "  generated (temp) run.sh: $tmp/run.sh"
  log "dry-run OK"
  exit 0
fi

if ! command -v systemctl >/dev/null 2>&1; then
  log "FATAL: systemctl not found — this installer targets systemd --user" >&2
  exit 1
fi

log "== build (release) =="
swift build -c release --package-path "$SWIFT_DIR"
[ -x "$BUILT_BIN" ] || { log "FATAL: build produced no $BUILT_BIN" >&2; exit 1; }

log "== install to $DAB_HOME =="
mkdir -p "$BIN_DIR" "$LOG_DIR" "$UNIT_DIR"
cp "$BUILT_BIN" "$BIN_DIR/dab"
chmod 0755 "$BIN_DIR/dab"

if [ ! -f "$ENV_FILE" ]; then
  cp "$ENV_EXAMPLE" "$ENV_FILE"
  chmod 0600 "$ENV_FILE"
  log "  created $ENV_FILE (0600) — fill in DISCORD_BOT_TOKEN and DAB_* before it can log in"
else
  log "  kept existing $ENV_FILE"
fi

gen_run_script "$RUN_SCRIPT"
gen_unit "$UNIT_FILE"
selfcheck "$UNIT_FILE" "$RUN_SCRIPT" 1

log "== register with systemd --user =="
systemctl --user daemon-reload
if ! systemctl --user enable --now "$SERVICE_NAME"; then
  log "FATAL: systemctl --user enable --now failed" >&2
  log "  unit: $UNIT_FILE" >&2
  exit 1
fi

# Linger: start at boot without an active login. Non-fatal (same as TS systemd.ts).
username="$(id -un)"
if ! loginctl enable-linger "$username" 2>/dev/null; then
  log "  note: loginctl enable-linger failed — may not auto-start before login"
  log "        if needed: sudo loginctl enable-linger $username"
fi

log "installed and started (systemd --user, Restart=always)."
log "  unit:  $UNIT_FILE"
log "  logs:  $OUT_LOG"
log "         $ERR_LOG"
log "  edit secrets: $ENV_FILE  (then: systemctl --user restart $SERVICE_NAME)"
log "  status: systemctl --user status $SERVICE_NAME"
